branches:
    only:
        - master

matrix:
    include:
        - language: generic
          sudo: true
          services:
              - docker
          install: docker info
          script: travis_wait 60 bash .ci/publish-image.sh
